### ISSUE TITLE
Upgrade Lunr.js to latest version

### ISSUE THREAD

**Issue by Charizard** [Charizard/ember-cli-lunr#6]

**Comment by st-h** [comment]
I came across this addon recently as I was requiring a way to search text within an ember app. Unfortunately the currently used lunr version is way too old to be useful. I was looking into updating the dependencies, however the main issue I am having is the now immutable index. Did you already think about a way to deal with that?

I was thinking about the following:
- we would need a way to get notified about changes to the store and a certain record type (the [RecordData rfc](https://github.com/igorT/rfcs/blob/17e8f97049452ae18d3b12ee23c4858a6d5e0bfd/text/0000-model-data.md) might be helpful here, but I haven't been able to figure out details so far)
- alternatively we could probably retrieve a record array from the store via `peekRecord` and observe changes to that array (as well as changes to the indexed fields)
- on every update to a record collection, we would need to build a new index (essentially just a simple json document)
- and load that index into lunr on every change to any record of a certain type (replacing the old index)

We could also have lunr build the index every time, but the[ docs already state](https://lunrjs.com/guides/index_prebuilding.html) that this could get slow.

I also posted to the ember-data discord channel and will update this issue in case I come along a better approach.

For now I think within my app I will be able to deal with directly importing lunr, but for an app-wide search a strategy like the one used by this addon certainly will be more useful.

**Comment by Charizard** [comment]
@st-h Hey Steve, thanks for already looking into this. I had been a bit busy and was unable to look into this. I will however allocate some time to look at this the immutable index issue by the end of this weekend and get back.

**Comment by duboff** [comment]
@Charizard, thanks for the update! Is it possible to release the new version on NPM?

**Comment by Charizard** [comment]
@duboff It should be released as v1.0.0 as this release has breaking changes. Let me know if you face any challenges.
